name: Deploy
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:

        - uses: actions/checkout@v2

        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: keveny/next_application
            tag-sha: true


        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

        - name: Bump version and push tag
          id: tagging
          uses: mathieudutour/github-tag-action@v4.5
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./app/container
            file: ./app/container/Dockerfile
            push: true
            platforms: linux/amd64
            tags: keveny/next_application:${{ steps.tagging.outputs.new_version }}
# ------------------------------------------------------------------------------------
        # - name: Install doctl
        #   uses: digitalocean/action-doctl@v2
        #   with:
        #     token: ${{ secrets.DIGITALOCEAN_TOKEN }}

        
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET }}
      #     aws-region: sa-east-1
# -------------------------------------------------------------------------------------------
        # - name: Setup kubectl
        #   uses: matootie/dokube@v1.3.2
        #   with:
        #     personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        #     clusterName: live-k8s

        # - name: set deployment image
        #   run: kubectl set image deployment next_server_application  docker=keveny/next_application:${{ steps.tagging.outputs.new_version }}
